### ISSUE TITLE
Protobuf patch has trailing whitespace triggering warning.

### ISSUE THREAD

**Issue by aregm** [intel-go/pysamprof#1]
Applying patch in Windows:
aregm@Barmaley MINGW64 /c/Projects/pysamprof (master)
$ cd 3rd_party/protobuf-c && git apply ../protobuf-c-vs2008-support.patch
../protobuf-c-vs2008-support.patch:36: trailing whitespace.

../protobuf-c-vs2008-support.patch:39: trailing whitespace.

warning: protobuf-c/protobuf-c.h has type 100644, expected 100755
warning: protoc-c/c_message.cc has type 100644, expected 100755
warning: 2 lines add whitespace errors.

**Comment by JustAMan** [comment]
Should be fixed with 02f760d6c37ef811f59633bcd67fd6a48886e62a

**Comment by vnlitvinov** [comment]
Should be fixed by 02f760d6c37ef811f59633bcd67fd6a48886e62a.
