### ISSUE TITLE
Converter does not work with Python 3.5.5

### ISSUE THREAD

**Issue by aregm** [intel-go/pysamprof#11]
(cudf) user@host:/pysamprof/pyext$ PYTHONPATH=../../pysamprof/3rd_party/protobuf/python/ python ../../pysamprof/trace_writer/python/raw2pprof.py --raw  ./result/trace/30920.0.raw  --symbols ./result/trace/30920.0.symraw --out ./result/pprof_out/trace.pprof --resolve
Traceback (most recent call last):
  File "../../pysamprof/trace_writer/python/raw2pprof.py", line 16, in <module>
    TYPE_UNDERFINEDF, TYPE_SAMPLE, TYPE_FUNCTION_INFO, TYPE_MAPPING = [struct.unpack('>i', tag)[0] for tag in 'UNDF SMPL FNCI MAPP'.split()]
  File "../../pysamprof/trace_writer/python/raw2pprof.py", line 16, in <listcomp>
    TYPE_UNDERFINEDF, TYPE_SAMPLE, TYPE_FUNCTION_INFO, TYPE_MAPPING = [struct.unpack('>i', tag)[0] for tag in 'UNDF SMPL FNCI MAPP'.split()]
TypeError: a bytes-like object is required, not 'str'

**Comment by vnlitvinov** [comment]
Closed by #12
