### ISSUE TITLE
Build instructions are incomplete.

### ISSUE THREAD

**Issue by aregm** [intel-go/pysamprof#2]
Build instructions are not working for Window/VS2017

**Comment by vnlitvinov** [comment]
It's possible to build on Windows with VS2008 (the only working for Python 2.7) starting with fadf0fa2fc6d3eced0566535a4e61fd5ddc38b35.
Newer VS support is coming soon.

**Comment by vnlitvinov** [comment]
Build instructions for Python 3.5 / Python 3.6 (using VS2015) are there starting from 078af6a0e824fded40dcfa02aef836980c268111.
VS2017 is required to have MSVC 14.0 installed (see https://wiki.python.org/moin/WindowsCompilers for more).
