### ISSUE TITLE
No instructions on how to use the tool

### ISSUE THREAD

**Issue by rscohn2** [intel-go/pysamprof#4]
A few lines in the README would help

**Comment by vnlitvinov** [comment]
I've added very basic usage, will add more soon.

**Comment by vnlitvinov** [comment]
Added two wiki pages:
* [Example of trace display on Ubuntu 18.04](https://github.com/intel-go/pysamprof/wiki/Example-of-trace-display-on-Ubuntu-18.04)
* [User API](https://github.com/intel-go/pysamprof/wiki/User-API) describing the extension API
